platform:
  - x86

install:
  - c:\"Program Files (x86)"\"Microsoft Visual Studio 12.0"\VC\vcvarsall.bat
  - git clone https://github.com/matricks/bam.git
  - cd bam
  - make_win64_msvc.bat
  - cd ..
  - bam\bam.exe config=debug
  - bam\bam.exe config=release
  - local\winx64\debug\getopt_tests.exe
  - local\winx64\release\getopt_tests.exe

build: off

